export const START_APPLICATION = 'START_APPLICATION';
export const CONFIG_LOADED = 'CONFIG_LOADED';
export const SEARCH_CONDITION_TRIGGER = 'SEARCH_CONDITION_TRIGGER';
export const RUN_EXPERIMENTS = 'RUN_EXPERIMENTS';
export const SELECT_EXP_TRIGGER = 'SELECT_EXP_TRIGGER';